spring.application.name=demotask

spring.datasource.url=jdbc:postgresql://localhost:5432/db_task
spring.datasource.username=postgres
spring.datasource.password=sa

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true